"""empty message

Revision ID: bf3f44d68296
Revises: 0018_increase_file_extension
Create Date: 2024-02-03 13:49:28.820592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3f44d68296'
down_revision = '0018_increase_file_extension'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moby_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('roms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moby_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roms', schema=None) as batch_op:
        batch_op.drop_column('moby_id')

    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_column('moby_id')

    # ### end Alembic commands ###
